import type { Metadata } from "next";
import AuthProvider from "@/components/AuthProvider";
import Header from "@/components/Header";
import "../globals.css";
 
export const metadata: Metadata = {
  title: "Skills Track -  Create Post",
  description: "Generated by create next app",
};

export default function CreateLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <Header />
      <main className="flex-1 flex flex-col">
        {children}
      </main>
      {/* <Footer /> */}
    </AuthProvider>
  );
}
