import Footer from '@/components/Footer';
import Header from '@/components/Header';
import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
  title: "Skills Track",
  description: "Generated by create next app",
};

const MainLayout = ({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) => {
  return (
    <>
      <Header />
      <main className="flex-1 bg-neutral-100 flex flex-col w-full">
        {children}
      </main>
      <Footer />
    </>
  )
}

export default MainLayout