import { AppSidebar } from '@/components/app-sidebar';
import Footer from '@/components/Footer';
import Header from '@/components/Header';
import { SidebarProvider } from '@/components/ui/sidebar';
import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
  title: "Skills Track",
  description: "Generated by create next app",
};

const DashboardLayout = ({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) => {
  return (
    <>
    <SidebarProvider>
        <AppSidebar />
        <main className="flex-1 bg-neutral-100 flex flex-col w-full">
            {children}
        </main>
    </SidebarProvider>
      
    </>
  )
}

export default DashboardLayout